import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Dashboard.module.css";
import { Button } from "@mui/material";
import { useRouter } from "next/router";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Dashboard() {
  const router = useRouter();

  const handleBackButton = () => {
    router.back();
  };

  return (
    <>
      <Head>
        <title>Virtual Nursing Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header />
        <div>
          <h1>Dashboard Page</h1>

          <div>
            <Button variant="contained" onClick={handleBackButton}>
              Back
            </Button>
          </div>
        </div>
      </main>
    </>
  );
}
